[package]
name = "tiny-skia"
version = "0.6.2"
authors = ["Yevhenii Reizner <razrfalcon@gmail.com>"]
edition = "2018"
description = "A tiny Skia subset ported to Rust."
documentation = "https://docs.rs/tiny-skia/"
readme = "README.md"
repository = "https://github.com/RazrFalcon/tiny-skia"
license = "BSD-3-Clause"
keywords = ["2d", "rendering", "skia"]
categories = ["rendering"]

[dependencies]
arrayref = "0.3"
# do not update to 0.6, because it requires Rust >= 1.51
arrayvec = { version = "0.5", default-features = false }
bytemuck = "1.4"
cfg-if = "1"
libm = { version = "0.2.1", optional = true }
png = { version = "0.17", optional = true }
# do not update to 0.6, because it requires Rust >= 1.51
safe_arch = { version = "0.5.2", features = ["bytemuck"], optional = true }

[features]
default = ["std", "simd", "png-format"]

# Enables the use of the standard library. Deactivate this and activate the libm
# feature to compile for targets that don't have std.
std = []

# Enables x86 SIMD instructions from SSE up to AVX2.
# Has no effect on non-x86 targets. Present mainly for testing.
simd = ["safe_arch"]

# Allows loading and saving `Pixmap` as PNG.
png-format = ["std", "png"]

[profile.release]
opt-level = 'z'
lto = true
codegen-units = 1